        {
            "name": "deferrable_enable",
            "friendly_name": "Deferrable Load enable",
            "type": "switch",
            "default": False,
        },
        {
            "name": "deferrable_max_energy",
            "friendly_name": "Deferrable Load max energy",
            "type": "input_number",
            "min": 0,
            "max": 30,
            "step": 0.1,
            "unit": "kWh",
            "enable": "deferrable_enable",
            "default": 2.0,
        },
        {
            "name": "deferrable_today",
            "friendly_name": "Deferrable Load today",
            "type": "input_number",
            "min": 0,
            "max": 30,
            "step": 0.1,
            "unit": "kWh",
            "enable": "deferrable_enable",
            "default": 0.0,
        },
        {
            "name": "deferrable_max_power",
            "friendly_name": "Deferrable Load max power",
            "type": "input_number",
            "min": 0,
            "max": 5000,
            "step": 100,
            "unit": "W",
            "enable": "deferrable_enable",
            "default": 1500,
        },
        {
            "name": "deferrable_min_power",
            "friendly_name": "Deferrable Load min power",
            "type": "input_number",
            "min": 0,
            "max": 5000,
            "step": 100,
            "unit": "W",
            "enable": "deferrable_enable",
            "default": 1000,
        },
        {
            "name": "deferrable_rate_threshold",
            "friendly_name": "Deferrable Load max rate price",
            "type": "input_number",
            "min": -10,
            "max": 1000,
            "step": 0.1,
            "unit": "p/kWh",
            "icon": "mdi:currency-usd",
            "enable": "deferrable_enable",
            "default": 100,
        },
        {
            "name": "deferrable_smart",
            "friendly_name": "Schedule Deferrable Load at lowest rates",
            "type": "switch",
            "enable": "deferrable_enable",
            "default": True,
        },
        {
            "name": "deferrable_smart_min_length",
            "friendly_name": "Deferrable Load smart min length",
            "type": "input_number",
            "min": 30,
            "max": 240,
            "step": 30,
            "unit": "minutes",
            "icon": "mdi:clock-outline",
            "enable": "deferrable_enable",
            "default": 60,
        },
        {
            "name": "deferrable_solar_priority",
            "friendly_name": "Prefer solar + battery over grid import",
            "type": "switch",
            "enable": "deferrable_enable",
            "default": True,
        },
        {
            "name": "deferrable_value_scaling",
            "friendly_name": "Deferrable Load value scaling",
            "type": "input_number",
            "min": 0,
            "max": 2.0,
            "step": 0.05,
            "unit": "*",
            "icon": "mdi:multiplication",
            "enable": "deferrable_enable",
            "default": 0.5,
        },
